with final as (

    select
    DATE_TIME_KEY,
	CAL_DATE,
	MEDIA_TYPE,
	DIRECTION,
	USER_ID,
	QUEUE_ID,
	DIVISION_ID,
	USER_DATA_KEY_1,
	USER_DATA_KEY_2,
	OFFERED,
	ACCEPTED,
	ACCEPTED_TIME,
	ACCEPTED_TIME_MAX,
	MET_THRESHOLD,
	NOT_RESPONDING,
	NOT_RESPONDING_TIME,
	NOT_RESPONDING_TIME_MAX,
	ALERT_TIME,
	HOLD_TIME,
	TALK_TIME,
	WRAP_TIME,
	HANDLE_TIME,
	TRANSFERRED_BLIND,
	TRANSFERRED_CONSULT

    from AGT_AGENT_QUEUE_SUBHR_SOURCE

)

select * from final