with final as (

SELECT 
   CONVERSATION_ID,
	DIVISION_ID,
	MEDIA_TYPE,
	DIRECTION,
	PARTICIPANT_ID,
	QUEUE_NAME,
	USER_NAME,
	START_TIMESTAMP,
	END_TIMESTAMP,
	DISCONNECT_TYPE,
	OFFERED,
	ABANDONED,
	SHORT_ABANDONED,
	ACCEPTED,
	MET_THRESHOLD,
	NOT_RESPONDING,
	ACD_TIME,
	NOT_RESPONDING_TIME,
	FLOW_OUT,
	ANSWERED_TIME,
	FLOW_OUT_TIME,
	ALERT,
	ALERT_TIME,
	HELD_TIME,
	TALK_TIME,
	WRAP_TIME,
	HANDLE_TIME,
	TRANSFERRED_BLIND,
	TRANSFERRED_CONSULT,
	AGENT_DISCONNECT
 
 FROM MEDIATIONSEGMENTFACT_SOURCE

)

select * from final